{{- if .Values.azure.client.default.account }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clustername | lower }}-azurefiles
data:
  azurestorageaccountname: {{ .Values.azure.client.default.account | b64enc }}
  azurestorageaccountkey: {{ required "Need to supply storage account access key for .Values.azure.client.default.account via --set azure.client.default.key=foo" .Values.azure.client.default.key | b64enc }}
{{- end }}
